### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by MohammadZarifiyan** [soketi/charts#16]
What is this package usage ?

Can i show metrics of websocket transactions in my website ? (ex: Transfered messages per hour, connections per hour, etc)

Also is there any documentation to better understanding this package ?

**Comment by rennokki** [comment]
This only works with Kubernetes. The metrics are available only if you're familiar with Prometheus, but we're hacking something to display metrics for non-Prometheus users too. 😁

**Comment by MohammadZarifiyan** [comment]
@rennokki Can you give me some tips on how to display statistics without using a Kubernetes?

**Comment by rennokki** [comment]
You can [enable Prometheus](https://docs.soketi.app/advanced-usage/scraping-prometheus-metrics) and query the `/metrics` endpoint as JSON:

```
http://localhost:9601/metrics?json=1
```

**Comment by MohammadZarifiyan** [comment]
@rennokki Thanks!
But is there any way to save statistics without querying `/metrics` every time ?
I want to save metrics of every app for each minutes into database.

**Comment by rennokki** [comment]
Currently not, we want to keep the application as stateless as possible.
